### ISSUE TITLE
[1.15] good

### ISSUE THREAD

**Issue by Yoghurt4C** [Yanis48/Mooblooms#3]
java.lang.IllegalStateException: No renderer registered for mooblooms:dandelion_moobloom
    at net.minecraft.class_898.<init>(class_898.java:199)
    at net.minecraft.class_310.<init>(class_310.java:485)
    at net.minecraft.client.main.Main.main(Main.java:164)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by Yanis48** [comment]
Seems the same as #4 , close this one as the other has the full report
